name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Check package.json version update
        uses: EndBug/version-check@v1.1.0
        id: check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Windows build
        if: steps.check.outputs.changed == 'true' && matrix.os == 'windows-latest'
        run: |
          npm install
          npm run build-win

      - name: Create tag for release
        if: steps.check.outputs.changed == 'true' && matrix.os == 'windows-latest'
        run: |
          git tag v${{ steps.check.outputs.version }}
          git push origin v${{ steps.check.outputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: steps.check.outputs.changed == 'true' && matrix.os == 'windows-latest'
        with:
          files: win.zip
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
