name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get package.json version
        uses: tyankatsu0105/read-package-version-actions@v1
        id: readPackageVersion

      - name: Verify if a tag exists for package.json version
        uses: mukunku/tag-exists-action@v1.0.0
        id: tagExists
        with:
          tag: 'v${{ steps.readPackageVersion.outputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new tag if it does not exist
        if: steps.tagExists.outputs.exists == 'false'
        id: stepVerifyNewTag
        run: |
          git tag v${{ steps.readPackageVersion.outputs.version }}
          git push origin v${{ steps.readPackageVersion.outputs.version }}
          echo '::set-output name=tagCreated::true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for windows if new tag created
        if: steps.stepVerifyNewTag.outputs.tagCreated == 'true'
        run: |
          npm install
          npm run build-win

      - name: Release if new tag created
        uses: softprops/action-gh-release@master
        if: steps.stepVerifyNewTag.outputs.tagCreated == 'true'
        with:
          files: win.zip
          tag_name: v${{ steps.readPackageVersion.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
